"""201 numeric reference cases generated by compiling the uploaded C++ sources.

This verifies the selected policy/centering/spacing sequences, not every possible
input and not Mini 4 Pro flight behavior. Kalman has separate invariant tests.
"""
import sys,json,math,unittest
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from follow_neo.policy import DeterministicTrackingPolicy,SmartTrackingController
from follow_neo.spacing import VisualSpacingController
from follow_neo.types import Intent,Kinematics,Settings


class CppReferenceTests(unittest.TestCase):
    def test_reference_sequences(self):
        rows=json.loads(Path(__file__).with_name('cpp_policy_reference.json').read_text())
        p=DeterministicTrackingPolicy(); settings=Settings()
        smart=SmartTrackingController(); spacing=VisualSpacingController()
        times=[1,2,2.05,2.1,2.5,2.8,3,3.8,4.7,6.09,6.2]
        for row in rows:
            i=row['index'];kind=row['kind'];state=None
            with self.subTest(kind=kind,index=i):
                if kind=='P':
                    t=times[i]; k=Kinematics(True,650 if i==5 else 320,240,80,60,150 if i==5 else 0,0)
                    mt=t if 1<=i<=3 else 2.1 if 4<=i<=5 else None
                    mid=i if 1<=i<=3 else 3 if 4<=i<=5 else None
                    cmd=p.update(t,k,640,480,mt,mid,Intent(.5,.25,.2,1) if 1<=i<=3 else Intent(),settings)
                    state=p.state
                elif kind=='S':
                    k=Kinematics(True,320+250*math.sin(i*.24),240+150*math.cos(i*.19),60+i*5,80,200*math.sin(i*.17),0)
                    cmd,_,_=smart.compute(k,640,480,.05,i%17==0,10+i*.05,settings)
                else:
                    t=20+i*.05;w=.05+i*.004
                    cmd,_=spacing.update(t,True,True,False,False,False,i+1,t-.02,.02,w,w,0,0,Intent(.1,0,0,.3),settings)
                    state=spacing.phase
                self.assertEqual(state,row['state'])
                for actual,expected in zip(vars(cmd).values(),row['intent']): self.assertAlmostEqual(actual,expected,places=9)


if __name__=='__main__': unittest.main(verbosity=2)
